### ISSUE TITLE
Doplnit úroveň znalosti jednotlivých technologies

### ISSUE THREAD

**Issue by Dominik-97** [Dominik-97/curriculum-vitae#1]

**Comment by Dominik-97** [comment]
Udělal sem zatím jako `&nbsp;\|&nbsp; <Level>`

Přemýšlím, jestli spíše neudělat jako `<level>` - tedy jako code block

**Comment by Dominik-97** [comment]
Popřípadě možnost udělat jako text s mezerou mezi schopností a levelem umu, tedy něco jako:

```css
.left {
    text-align: left; 
    width:50%; 
    display: inline-block; 
    left: 1.25em !important;
}

.right {
    text-align: right; 
    width:10%;  
    display: inline-block; 
    margin-left: -200px;">
}
```

A poté v html použít následující:

```html
<li>
   <p class="left">UM</p>
   <p class="right">LEVEL</p>
</li>
```
